# -*- coding: utf-8 -*-
"""CapstoneProjectCustomerOrder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnYbyGXhtaonbNl9zyqZxa6BiL_e6PAa
"""

from pyspark.sql import SparkSession

spark= SparkSession.builder.appName("CapstoneProjectCustomerOrder").getOrCreate()

spark

# Load order and delivery data into PySpark
orders_df = spark.read.csv("orders.csv", header=True, inferSchema=True)
delivery_df = spark.read.csv("delivery_status.csv", header=True, inferSchema=True)
customers_df = spark.read.csv("customers.csv", header=True, inferSchema=True)
orders_df.show()
delivery_df.show()
customers_df.show()
# Join orders and customer tables
orders_customers_df = orders_df.join(customers_df, on="customer_id", how="inner")
orders_customers_df.show()
# Group by region to count delays
delays_by_region_df = orders_customers_df.join(delivery_df, on="order_id", how="inner")
delays_by_region_df.show()
# Save results to a file
delays_by_region_df.write.csv("delays_by_region.csv", header=True)

spark.stop()